Revert "UPSTREAM: NFS: Add a mount option "softerr" to allow clients to see ETIMEDOUT errors"
Fixes a compile error when NFS_FS is enabled

../fs/nfs/client.c:613:19: error: no member named 'cl_softerr' in 'struct rpc_clnt'
  613 |                 server->client->cl_softerr = 1;
      |                 ~~~~~~~~~~~~~~  ^
1 error generated.

This reverts commit b47d2aad49ed547a3690950c86bde599ccfacbae.